<?php

namespace App\Helpers;

class PermissionHelper
{
    const USER_CREATE = "USER_CREATE";
    const USER_UPDATE = "USER_UPDATE";
    const USER_VIEW_ANY = "USER_VIEW_ANY";
    const USER_VIEW = "USER_VIEW";
    const USER_SYNC_ROLE = "USER_SYNC_ROLE";
    const USER_SYNC_PERMISSION = "USER_SYNC_PERMISSION";
    const ROLE_VIEW_ANY = "ROLE_VIEW_ANY";
    const ROLE_VIEW = "ROLE_VIEW";
    const ROLE_CREATE = "ROLE_CREATE";
    const ROLE_UPDATE = "ROLE_UPDATE";
    const ROLE_DELETE = "ROLE_DELETE";
    const ROLE_SYNC_PERMISSION = "ROLE_SYNC_PERMISSION";
    const PERMISSION_VIEW_ANY = "PERMISSION_VIEW_ANY";
    const PERMISSION_VIEW = "PERMISSION_VIEW";
    const PERMISSION_CREATE = "PERMISSION_CREATE";
    const PERMISSION_UPDATE = "PERMISSION_UPDATE";
    const PERMISSION_DELETE = "PERMISSION_DELETE";
}
